/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BlastRouteImport } from './routes/blast'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlastIndexRouteImport } from './routes/blast/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as BlastDashboardRouteImport } from './routes/blast/dashboard'
import { Route as BlastCreateRouteImport } from './routes/blast/create'
import { Route as BlastCampaignsRouteImport } from './routes/blast/campaigns'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppScenesRouteImport } from './routes/app/scenes'
import { Route as AppMyListRouteImport } from './routes/app/my-list'
import { Route as AppLiveRouteImport } from './routes/app/live'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as BlastCampaignsIdRouteImport } from './routes/blast/campaigns.$id'
import { Route as AppTitleIdRouteImport } from './routes/app/title.$id'
import { Route as AuthenticatedWatchIdRouteImport } from './routes/_authenticated/watch.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastRoute = BlastRouteImport.update({
  id: '/blast',
  path: '/blast',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlastIndexRoute = BlastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlastRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BlastDashboardRoute = BlastDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BlastRoute,
} as any)
const BlastCreateRoute = BlastCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BlastRoute,
} as any)
const BlastCampaignsRoute = BlastCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => BlastRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppScenesRoute = AppScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyListRoute = AppMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const BlastCampaignsIdRoute = BlastCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BlastCampaignsRoute,
} as any)
const AppTitleIdRoute = AppTitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedWatchIdRoute = AuthenticatedWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blast': typeof BlastRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/scenes': typeof AppScenesRoute
  '/app/search': typeof AppSearchRoute
  '/blast/campaigns': typeof BlastCampaignsRouteWithChildren
  '/blast/create': typeof BlastCreateRoute
  '/blast/dashboard': typeof BlastDashboardRoute
  '/app/': typeof AppIndexRoute
  '/blast/': typeof BlastIndexRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/blast/campaigns/$id': typeof BlastCampaignsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/scenes': typeof AppScenesRoute
  '/app/search': typeof AppSearchRoute
  '/blast/campaigns': typeof BlastCampaignsRouteWithChildren
  '/blast/create': typeof BlastCreateRoute
  '/blast/dashboard': typeof BlastDashboardRoute
  '/app': typeof AppIndexRoute
  '/blast': typeof BlastIndexRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/blast/campaigns/$id': typeof BlastCampaignsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/blast': typeof BlastRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/scenes': typeof AppScenesRoute
  '/app/search': typeof AppSearchRoute
  '/blast/campaigns': typeof BlastCampaignsRouteWithChildren
  '/blast/create': typeof BlastCreateRoute
  '/blast/dashboard': typeof BlastDashboardRoute
  '/app/': typeof AppIndexRoute
  '/blast/': typeof BlastIndexRoute
  '/_authenticated/watch/$id': typeof AuthenticatedWatchIdRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/blast/campaigns/$id': typeof BlastCampaignsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blast'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app/live'
    | '/app/my-list'
    | '/app/scenes'
    | '/app/search'
    | '/blast/campaigns'
    | '/blast/create'
    | '/blast/dashboard'
    | '/app/'
    | '/blast/'
    | '/watch/$id'
    | '/app/title/$id'
    | '/blast/campaigns/$id'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/app/live'
    | '/app/my-list'
    | '/app/scenes'
    | '/app/search'
    | '/blast/campaigns'
    | '/blast/create'
    | '/blast/dashboard'
    | '/app'
    | '/blast'
    | '/watch/$id'
    | '/app/title/$id'
    | '/blast/campaigns/$id'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/blast'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/app/live'
    | '/app/my-list'
    | '/app/scenes'
    | '/app/search'
    | '/blast/campaigns'
    | '/blast/create'
    | '/blast/dashboard'
    | '/app/'
    | '/blast/'
    | '/_authenticated/watch/$id'
    | '/app/title/$id'
    | '/blast/campaigns/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BlastRoute: typeof BlastRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blast': {
      id: '/blast'
      path: '/blast'
      fullPath: '/blast'
      preLoaderRoute: typeof BlastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blast/': {
      id: '/blast/'
      path: '/'
      fullPath: '/blast/'
      preLoaderRoute: typeof BlastIndexRouteImport
      parentRoute: typeof BlastRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/blast/dashboard': {
      id: '/blast/dashboard'
      path: '/dashboard'
      fullPath: '/blast/dashboard'
      preLoaderRoute: typeof BlastDashboardRouteImport
      parentRoute: typeof BlastRoute
    }
    '/blast/create': {
      id: '/blast/create'
      path: '/create'
      fullPath: '/blast/create'
      preLoaderRoute: typeof BlastCreateRouteImport
      parentRoute: typeof BlastRoute
    }
    '/blast/campaigns': {
      id: '/blast/campaigns'
      path: '/campaigns'
      fullPath: '/blast/campaigns'
      preLoaderRoute: typeof BlastCampaignsRouteImport
      parentRoute: typeof BlastRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scenes': {
      id: '/app/scenes'
      path: '/scenes'
      fullPath: '/app/scenes'
      preLoaderRoute: typeof AppScenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-list': {
      id: '/app/my-list'
      path: '/my-list'
      fullPath: '/app/my-list'
      preLoaderRoute: typeof AppMyListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/blast/campaigns/$id': {
      id: '/blast/campaigns/$id'
      path: '/$id'
      fullPath: '/blast/campaigns/$id'
      preLoaderRoute: typeof BlastCampaignsIdRouteImport
      parentRoute: typeof BlastCampaignsRoute
    }
    '/app/title/$id': {
      id: '/app/title/$id'
      path: '/title/$id'
      fullPath: '/app/title/$id'
      preLoaderRoute: typeof AppTitleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/watch/$id': {
      id: '/_authenticated/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AuthenticatedWatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedWatchIdRoute: typeof AuthenticatedWatchIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedWatchIdRoute: AuthenticatedWatchIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AppRouteChildren {
  AppLiveRoute: typeof AppLiveRoute
  AppMyListRoute: typeof AppMyListRoute
  AppScenesRoute: typeof AppScenesRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTitleIdRoute: typeof AppTitleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLiveRoute: AppLiveRoute,
  AppMyListRoute: AppMyListRoute,
  AppScenesRoute: AppScenesRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppTitleIdRoute: AppTitleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlastCampaignsRouteChildren {
  BlastCampaignsIdRoute: typeof BlastCampaignsIdRoute
}

const BlastCampaignsRouteChildren: BlastCampaignsRouteChildren = {
  BlastCampaignsIdRoute: BlastCampaignsIdRoute,
}

const BlastCampaignsRouteWithChildren = BlastCampaignsRoute._addFileChildren(
  BlastCampaignsRouteChildren,
)

interface BlastRouteChildren {
  BlastCampaignsRoute: typeof BlastCampaignsRouteWithChildren
  BlastCreateRoute: typeof BlastCreateRoute
  BlastDashboardRoute: typeof BlastDashboardRoute
  BlastIndexRoute: typeof BlastIndexRoute
}

const BlastRouteChildren: BlastRouteChildren = {
  BlastCampaignsRoute: BlastCampaignsRouteWithChildren,
  BlastCreateRoute: BlastCreateRoute,
  BlastDashboardRoute: BlastDashboardRoute,
  BlastIndexRoute: BlastIndexRoute,
}

const BlastRouteWithChildren = BlastRoute._addFileChildren(BlastRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BlastRoute: BlastRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
