/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppMyListRouteImport } from './routes/app/my-list'
import { Route as AppLiveRouteImport } from './routes/app/live'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AppTitleIdRouteImport } from './routes/app/title.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicRokuFeedRouteImport } from './routes/api/public/roku-feed'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as ApiMuxWebhookRouteImport } from './routes/api/mux/webhook'
import { Route as AuthenticatedWatchIdRouteImport } from './routes/_authenticated/watch.$id'
import { Route as ApiPublicHlsSplatRouteImport } from './routes/api/public/hls.$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMyListRoute = AppMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AppTitleIdRoute = AppTitleIdRouteImport.update({
  id: '/title/$id',
  path: '/title/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRokuFeedRoute = ApiPublicRokuFeedRouteImport.update({
  id: '/api/public/roku-feed',
  path: '/api/public/roku-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMuxWebhookRoute = ApiMuxWebhookRouteImport.update({
  id: '/api/mux/webhook',
  path: '/api/mux/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchIdRoute = AuthenticatedWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHlsSplatRoute = ApiPublicHlsSplatRouteImport.update({
  id: '/api/public/hls/$',
  path: '/api/public/hls/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/roku-feed': typeof ApiPublicRokuFeedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/search': typeof AppSearchRoute
  '/app': typeof AppIndexRoute
  '/watch/$id': typeof AuthenticatedWatchIdRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/roku-feed': typeof ApiPublicRokuFeedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/redirect': typeof RedirectRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app/live': typeof AppLiveRoute
  '/app/my-list': typeof AppMyListRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/_authenticated/watch/$id': typeof AuthenticatedWatchIdRoute
  '/api/mux/webhook': typeof ApiMuxWebhookRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/roku-feed': typeof ApiPublicRokuFeedRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/app/title/$id': typeof AppTitleIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/api/public/hls/$': typeof ApiPublicHlsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/app/live'
    | '/app/my-list'
    | '/app/search'
    | '/app/'
    | '/watch/$id'
    | '/api/mux/webhook'
    | '/api/public/geo'
    | '/api/public/roku-feed'
    | '/api/stripe/webhook'
    | '/app/title/$id'
    | '/admin/'
    | '/dashboard/'
    | '/api/public/hls/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/app/live'
    | '/app/my-list'
    | '/app/search'
    | '/app'
    | '/watch/$id'
    | '/api/mux/webhook'
    | '/api/public/geo'
    | '/api/public/roku-feed'
    | '/api/stripe/webhook'
    | '/app/title/$id'
    | '/admin'
    | '/dashboard'
    | '/api/public/hls/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/redirect'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/admin'
    | '/app/live'
    | '/app/my-list'
    | '/app/search'
    | '/app/'
    | '/_authenticated/watch/$id'
    | '/api/mux/webhook'
    | '/api/public/geo'
    | '/api/public/roku-feed'
    | '/api/stripe/webhook'
    | '/app/title/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/api/public/hls/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RedirectRoute: typeof RedirectRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiMuxWebhookRoute: typeof ApiMuxWebhookRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicRokuFeedRoute: typeof ApiPublicRokuFeedRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPublicHlsSplatRoute: typeof ApiPublicHlsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-list': {
      id: '/app/my-list'
      path: '/my-list'
      fullPath: '/app/my-list'
      preLoaderRoute: typeof AppMyListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live': {
      id: '/app/live'
      path: '/live'
      fullPath: '/app/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/app/title/$id': {
      id: '/app/title/$id'
      path: '/title/$id'
      fullPath: '/app/title/$id'
      preLoaderRoute: typeof AppTitleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/roku-feed': {
      id: '/api/public/roku-feed'
      path: '/api/public/roku-feed'
      fullPath: '/api/public/roku-feed'
      preLoaderRoute: typeof ApiPublicRokuFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mux/webhook': {
      id: '/api/mux/webhook'
      path: '/api/mux/webhook'
      fullPath: '/api/mux/webhook'
      preLoaderRoute: typeof ApiMuxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watch/$id': {
      id: '/_authenticated/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AuthenticatedWatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hls/$': {
      id: '/api/public/hls/$'
      path: '/api/public/hls/$'
      fullPath: '/api/public/hls/$'
      preLoaderRoute: typeof ApiPublicHlsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedWatchIdRoute: typeof AuthenticatedWatchIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedWatchIdRoute: AuthenticatedWatchIdRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AppRouteChildren {
  AppLiveRoute: typeof AppLiveRoute
  AppMyListRoute: typeof AppMyListRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTitleIdRoute: typeof AppTitleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLiveRoute: AppLiveRoute,
  AppMyListRoute: AppMyListRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppTitleIdRoute: AppTitleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RedirectRoute: RedirectRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiMuxWebhookRoute: ApiMuxWebhookRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicRokuFeedRoute: ApiPublicRokuFeedRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPublicHlsSplatRoute: ApiPublicHlsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
